### ISSUE TITLE
After upgrade python 3.6.5 have below error message

### ISSUE THREAD

**Issue by makakin** [MISP/mail_to_misp#20]
I follow the instruction of installation guide, the help manual show as correctly. However, when the command without the -h, the error message show as below.

$ ./mail_to_misp.py -h
usage: mail_to_misp.py [-h] [-r READ] [-t] [infile]

Push a Mail into a MISP instance

positional arguments:
  infile

optional arguments:
  -h, --help            show this help message and exit
  -r READ, --read READ  Read from tempfile.
  -t, --trap            Import the Email as-is.

----

$ ./mail_to_misp.py

Traceback (most recent call last):
  File "./mail_to_misp.py", line 384, in <module>
    raise Exception('This is not implemented anymore.')
Exception: This is not implemented anymore.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "./mail_to_misp.py", line 384, in <module>
    raise Exception('This is not implemented anymore.')
Exception: This is not implemented anymore.

**Comment by makakin** [comment]
Fixed the ModuleNotFoundError: No module named 'apt_pkg'
$ cd /usr/lib/python3/dist-packages/
$ sudo ln -s apt_pkg.cpython-{35m,36m}-x86_64-linux-gnu.so

However, still cannot run properly
From mail.log
... relay=local, delay=1.8, delays=1/0.01/0/0.79, dsn=5.3.0, status=bounced (Command died with status 1: "/mail_to_misp.py". Command output: Traceback (most recent call last):   File "/mail_to_misp.py", line 384, in <module>     raise Exception('This is not implemented anymore.') Exception: This is not implemented anymore. )

**Comment by rommelfs** [comment]
Please change the call in the /etc/aliases file to the following format:
misp_handler: "|/path/to/mail_to_misp.py -"
(mind the '-' at the end).

Documentation has been updated.
