### ISSUE TITLE
Attachment that are text files break the script

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/mail_to_misp#27]
If there is an attachment that is just a text file it will break the script.

```
Traceback (most recent call last): File "/opt/misp_addons/mail_to_misp/mail_to_misp.py", line 65, in <module> mail2misp.process_email_body() File "/opt/misp_addons/mail_to_misp/mail2misp/mail2misp.py", line 151, in process_email_body self._find_attached_forward() File "/opt/misp_addons/mail_to_misp/mail2misp/mail2misp.py", line 85, in _find_attached_forward f_object, main_object, sections = make_binary_objects(pseudofile=BytesIO(attachment.get_content()), filename=filename, standalone=False) TypeError: a bytes-like object is required, not 'str'> #SMTP#
```

**Comment by robertnixon2003** [comment]
Still doesn't work with .txt file or .csv file.

**Comment by Rafiot** [comment]
Woops, right, thanks. This commit should fix it: https://github.com/MISP/mail_to_misp/commit/45fa0c7323bf1f77cd9f8f4c6fa9d020d156932b
